--====================================================================================================================
/*
LAS RELACIONES UNO A UNO SON LAS TABLAS 
PERSONAS - SUELDO
SUELDO - RESUMEN_TOTAL_MENSUAL
LAS RELACIONES DE UNO A MUCHOS ESTAN LAS
 TITULO - PERSONAS
 DEPENDENCIA - PERSONAS
 CATEGORIA - PERSONAS
LAS RELACIONES MUCHOS A MUCHOS SON LAS
TITULO - DEPENDENCIA_TITULO - DEPENDENCIA

*/
--==============================================================================================================

USE MASTER
GO
drop database ACTIVIDAD_1_2
go

CREATE DATABASE ACTIVIDAD_1_2
GO
USE ACTIVIDAD_1_2
GO
CREATE TABLE Dependencia(
	ID_DESTINO VARCHAR(4) PRIMARY KEY,
	DESCRIPCION VARCHAR(50) NOT NULL,
	PORCENTAJE INT NOT NULL CHECK(PORCENTAJE >= 0)
)
GO
CREATE TABLE Categoria(
	ID_CATEGORIA VARCHAR(2) PRIMARY KEY,
	DESCRIPCION VARCHAR(30) NOT NULL,
	SUELDO FLOAT NOT NULL CHECK(SUELDO >0)
)
GO
CREATE TABLE Titulo(
	ID_TITULO VARCHAR(4) PRIMARY KEY,
	DESCRIP_TITULO VARCHAR(60) NOT NULL,
	NIVEL VARCHAR(15) NOT NULL CHECK(NIVEL = 'SECUNDARIO' OR NIVEL = 'TERCIARIO' OR NIVEL = 'UNIVERSITARIO'),
	PORCENTAJE INT NOT NULL DEFAULT(10)
)
GO
CREATE TABLE Personas(
    CUIL VARCHAR(15) PRIMARY KEY,
    APELLDO_NOMBRE VARCHAR(60) NOT NULL,
    SEXO VARCHAR(10) NOT NULL CHECK(SEXO = 'FEMENIMO' OR SEXO = 'MASCULINO' OR SEXO = 'OTRO'),
    ESCALAFON VARCHAR(2) NOT NULL,
	FECHA_INGRESO DATE NOT NULL CHECK(FECHA_INGRESO < GETDATE()),
	DEPENDENCIA VARCHAR(4) NOT NULL FOREIGN KEY REFERENCES Dependencia(ID_DESTINO),
	CATEGORIA VARCHAR(2) NOT NULL FOREIGN KEY REFERENCES Categoria(ID_CATEGORIA),
	TITULO VARCHAR(4) FOREIGN KEY REFERENCES Titulo(ID_TITULO),
	SIT_REVISTA BIT NOT NULL --SIT REVISTA 0 = PASIVA, 1 = ACTIVIDAD
)
GO
DROP table Sueldo
CREATE TABLE Sueldo( -- POR TRIGGER SE INGRESAN LOS VALORES QUE CORRESPONDE A CADA ITEM DEL SUELDO
	CUIL VARCHAR(15),
	IMP_SUELDO FLOAT,
	ANTIGUEDAD INT, --MUESTRA LA CANT AÑOS PARA MOSTRAR EN EL RECIBO
	IMP_ANTIGUEDAD FLOAT,
	TITULO FLOAT,
	IMP_REINTEGRO_GANANCIA FLOAT,
	
)
GO
--Ingreso propiedades de los campos
ALTER TABLE Sueldo ALTER COLUMN CUIL VARCHAR(15) NOT NULL
ALTER TABLE Sueldo ALTER COLUMN IMP_SUELDO FLOAT NOT NULL
ALTER TABLE Sueldo ALTER COLUMN ANTIGUEDAD INT NOT NULL
ALTER TABLE Sueldo ALTER COLUMN IMP_ANTIGUEDAD FLOAT NOT NULL
ALTER TABLE Sueldo ALTER COLUMN IMP_TITULO FLOAT NOT NULL
ALTER TABLE Sueldo ALTER COLUMN IMP_REINTEGRO_GANANCIA FLOAT NOT NULL
--Ingreso Constraint
ALTER TABLE Sueldo ADD CONSTRAINT FK_CUIL FOREIGN KEY (CUIL) REFERENCES Personas(CUIL) --AGREGRO FOREIGN KEY
ALTER TABLE Sueldo ADD CONSTRAINT PK_CUIL PRIMARY KEY (CUIL)

ALTER TABLE Sueldo ADD CONSTRAINT CH_MAYOR_CERO CHECK(IMP_SUELDO >= 0), CHECK(ANTIGUEDAD >= 0), CHECK(IMP_ANTIGUEDAD >= 0), CHECK(IMP_TITULO >= 0), CHECK(IMP_REINTEGRO_GANANCIA >= 0)
--Otras Funciones
TRUNCATE TABLE Sueldo
ALTER TABLE Sueldo DROP CONSTRAINT FK_CUIL
sp_RENAME 'Sueldo.TITULO', 'IMP_TITULO', 'COLUMN'
GO
--Agrego nuevo Campo
ALTER TABLE Sueldo ADD CATEGORIA VARCHAR(2) NOT NULL 
ALTER TABLE Sueldo ADD CONSTRAINT CH_CATEGORIA CHECK(CATEGORIA >= 0)
GO

CREATE TABLE Resumen_Totales_Mensual(
	CUIL VARCHAR(15) FOREIGN KEY REFERENCES Sueldo(CUIL) UNIQUE,
	TOTAL_BRUTO FLOAT NOT NULL CHECK(TOTAL_BRUTO >= 0),
	IMP_APORTES FLOAT NOT NULL CHECK(IMP_APORTES >= 0),
	IMP_SEGUROS FLOAT NOT NULL CHECK(IMP_SEGUROS >= 0),
	IMP_DESC_GANANCIA FLOAT NOT NULL CHECK(IMP_DESC_GANANCIA >= 0),
	TOTAL_DESCUENTOS FLOAT NOT NULL CHECK(TOTAL_DESCUENTOS >= 0),
	TOTAL_NETOS FLOAT NOT NULL CHECK(TOTAL_NETOS >= 0),
	IMP_CONTRIBUCIONES FLOAT NOT NULL CHECK(IMP_CONTRIBUCIONES >= 0),
)
GO
DROP TABLE Dependencia_Titulo
CREATE TABLE Dependencia_Titulo( --ES UN RESUMEN ENTRE LAS DOS TABALAS DEPENDENCIA Y TITULO LA CANTIDAD POR TITULO Y CATEGORIA
    ID_TITULO VARCHAR(4) FOREIGN KEY REFERENCES Titulo(ID_TITULO),
    ID_DESTINO VARCHAR(4) FOREIGN KEY REFERENCES Dependencia(ID_DESTINO),
    CANT_PERSONAL_CATEGORIA INT NOT NULL CHECK(CANT_PERSONAL_CATEGORIA >= 0),
    PRIMARY KEY (ID_TITULO, ID_DESTINO)
)
--Otra forma
ALTER TABLE Dependencia_Titulo ADD CONSTRAINT PRIMARY KEY(ID_TITULO, ID_DESTINO)
--==============================================================================================================
